version: "3.6"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: on-failure
    networks:
      - tki-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/root/certs/
    ports:
      - 80:80
      - 443:443

  rstudio:
    image: rocker/tidyverse:3.5.2
    container_name: rstudio
    restart: on-failure
    volumes:
      - type: volume
        source: rstudio
        target: /home/rstudio
        volume:
          no-copy: true
      - type: bind
        source: ./projects
        target: /home/rstudio/projects
      - type: volume
        source: r_libs
        target: /usr/local/lib/R
        volume:
          no-copy: true
    networks:
      - tki-net
    environment:
      - PASSWORD=rstudio1
    expose:
      - 8787

networks:
  tki-net:
    name: tki-net

volumes:
  r_libs:
  rstudio:
